-- SAGO 백엔드 초기 스키마 (baseline)
--
-- 손으로 쓰지 않고 엔티티 메타데이터에서 PostgreSQL DDL로 뽑아낸 것이다.
-- 손으로 쓰면 인덱스와 유니크 제약이 빠지기 쉬운데, 그중 일부는 동시 요청 방어에
-- 실제로 쓰이고 있어(중복 가입 차단, refresh 토큰 회전 경합 판정) 빠지면
-- 그 방어가 조용히 사라진다. 테스트는 H2에서 엔티티로 스키마를 만들기 때문에
-- 그 누락을 잡아주지 못한다.
--
-- 이 파일은 이미 적용된 마이그레이션이므로 수정하지 않는다.
-- 이후 스키마 변경은 V2__, V3__ 으로 쌓는다.


    create table accident (
        latitude numeric(10,7),
        longitude numeric(10,7),
        accident_id bigint generated by default as identity,
        created_at timestamp(6) not null,
        occurred_at timestamp(6) not null,
        user_id bigint not null,
        injury_other varchar(10) check (injury_other in ('NONE','MINOR','SEVERE')),
        injury_self varchar(10) check (injury_self in ('NONE','MINOR','SEVERE')),
        accident_type varchar(20) not null check (accident_type in ('PERSONAL','VEHICLE','SINGLE','HIT_AND_RUN')),
        status varchar(20) not null check (status in ('IN_PROGRESS','COMPLETED','CANCELLED')),
        direction varchar(50),
        road_condition varchar(100),
        memo TEXT,
        primary key (accident_id)
    );

    create table capture_decision (
        is_required boolean not null,
        accident_id bigint not null,
        created_at timestamp(6) not null,
        decision_id bigint generated by default as identity,
        decided_by varchar(10) not null check (decided_by in ('AI','USER')),
        reason varchar(255),
        primary key (decision_id)
    );

    create table checklist_item (
        is_completed boolean not null,
        order_no integer not null,
        accident_id bigint not null,
        checklist_item_id bigint generated by default as identity,
        completed_at timestamp(6),
        source varchar(10) not null check (source in ('AI','STATIC')),
        content varchar(100) not null,
        primary key (checklist_item_id)
    );

    create table contact_log (
        accident_id bigint not null,
        contact_id bigint generated by default as identity,
        contacted_at timestamp(6) not null,
        contact_type varchar(20) not null check (contact_type in ('EMERGENCY_112','EMERGENCY_119','INSURANCE')),
        primary key (contact_id)
    );

    create table photo (
        latitude numeric(10,7),
        longitude numeric(10,7),
        accident_id bigint not null,
        created_at timestamp(6) not null,
        photo_id bigint generated by default as identity,
        taken_at timestamp(6),
        category varchar(50),
        file_url varchar(512) not null,
        primary key (photo_id)
    );

    create table photo_tag (
        confidence numeric(5,2),
        is_manual boolean not null,
        photo_id bigint not null,
        tag_id bigint generated by default as identity,
        tag_type varchar(10) not null check (tag_type in ('DAMAGE','OBJECT')),
        label varchar(100) not null,
        primary key (tag_id)
    );

    create table refresh_token (
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        token_id bigint generated by default as identity,
        user_id bigint not null,
        token_hash varchar(64) not null,
        primary key (token_id),
        constraint uk_refresh_token_hash unique (token_hash)
    );

    create table report (
        version integer not null,
        accident_id bigint not null,
        created_at timestamp(6) not null,
        report_id bigint generated by default as identity,
        status varchar(10) not null check (status in ('DRAFT','CONFIRMED')),
        pdf_url varchar(512),
        disclaimer varchar(255) not null,
        narrative TEXT not null,
        primary key (report_id)
    );

    create table report_summary (
        line_no integer not null,
        report_id bigint not null,
        content varchar(255) not null,
        primary key (line_no, report_id)
    );

    create table report_unverified_item (
        line_no integer not null,
        report_id bigint not null,
        content varchar(255) not null,
        primary key (line_no, report_id)
    );

    create table social_auth (
        created_at timestamp(6) not null,
        social_auth_id bigint generated by default as identity,
        user_id bigint not null,
        provider varchar(10) not null check (provider in ('KAKAO','GOOGLE')),
        provider_user_id varchar(100) not null,
        primary key (social_auth_id),
        constraint uk_social_auth_provider_user unique (provider, provider_user_id)
    );

    create table statement (
        accident_id bigint not null,
        created_at timestamp(6) not null,
        statement_id bigint generated by default as identity,
        audio_file_url varchar(512) not null,
        stt_text TEXT,
        primary key (statement_id)
    );

    create table supplement_question (
        accident_id bigint not null,
        created_at timestamp(6) not null,
        question_id bigint generated by default as identity,
        round varchar(10) not null check (round in ('INITIAL','ADDITIONAL')),
        answer TEXT,
        question varchar(255) not null,
        primary key (question_id)
    );

    create table terms_agreement (
        is_agreed boolean not null,
        agreed_at timestamp(6) not null,
        agreement_id bigint generated by default as identity,
        user_id bigint not null,
        terms_type varchar(20) not null check (terms_type in ('SERVICE','PRIVACY','LOCATION','MARKETING')),
        version varchar(20) not null,
        primary key (agreement_id)
    );

    create table "user" (
        email_verified boolean default false not null not null,
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        user_id bigint generated by default as identity,
        bike_number varchar(20),
        bike_model varchar(100),
        nickname varchar(100),
        profile_image_url varchar(512),
        email varchar(255) not null,
        primary key (user_id)
    );

    create index idx_accident_user_occurred 
       on accident (user_id, occurred_at);

    create index idx_checklist_item_accident_order 
       on checklist_item (accident_id, order_no);

    create index idx_contact_log_accident_contacted 
       on contact_log (accident_id, contacted_at);

    create index idx_photo_accident_created 
       on photo (accident_id, created_at, photo_id);

    create index idx_statement_accident_created 
       on statement (accident_id, created_at);

    create index idx_terms_agreement_user_type 
       on terms_agreement (user_id, terms_type);

    alter table if exists accident 
       add constraint FKi6ptv3ne1idl776rlelrk1kas 
       foreign key (user_id) 
       references "user";

    alter table if exists capture_decision 
       add constraint FKjofj5ece86oe8hb3vcmlvaqbr 
       foreign key (accident_id) 
       references accident;

    alter table if exists checklist_item 
       add constraint FK82iq4rfjvtwo0y0ao7tth1gjx 
       foreign key (accident_id) 
       references accident;

    alter table if exists contact_log 
       add constraint FKfaest5gpeaevvnbn7sjs61ag8 
       foreign key (accident_id) 
       references accident;

    alter table if exists photo 
       add constraint FKrlxp497mkinw1ln6fbnqqgpih 
       foreign key (accident_id) 
       references accident;

    alter table if exists photo_tag 
       add constraint FKs4r7gs7o22avi74h7oopch1ag 
       foreign key (photo_id) 
       references photo;

    alter table if exists refresh_token 
       add constraint FK172n6374f2cgiei2vtvjw2fak 
       foreign key (user_id) 
       references "user";

    alter table if exists report 
       add constraint FKnemtr57fvgbbqn071b0bymsqq 
       foreign key (accident_id) 
       references accident;

    alter table if exists report_summary 
       add constraint FK3gmkus1lrg0bqw03vvv2ja4ck 
       foreign key (report_id) 
       references report;

    alter table if exists report_unverified_item 
       add constraint FKj18xu2orsjogckuls0j36r7r8 
       foreign key (report_id) 
       references report;

    alter table if exists social_auth 
       add constraint FKddq1m77n2l114202qqixbug2 
       foreign key (user_id) 
       references "user";

    alter table if exists statement 
       add constraint FKny8fc4tt8u97099c94qv5ik2o 
       foreign key (accident_id) 
       references accident;

    alter table if exists supplement_question 
       add constraint FK305if5fjmfo5v6old3hd1abt3 
       foreign key (accident_id) 
       references accident;

    alter table if exists terms_agreement 
       add constraint FKo6rkxl84gpcnx6nxljy4yjfqc 
       foreign key (user_id) 
       references "user";
